---
- name: Desplegar Oracle Database 23c AI con base de datos personalizada
  hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml
  roles:
    - common
    - oracle_install
    - instituto_db
