---
- name: Desplegar Oracle Database 23c AI en Oracle Linux 9.x
  hosts: oracle_servers
  become: yes
  vars_files:
    - group_vars/all.yml
  roles:
    - common
    - oracle_install
    - oracle_cdb
