---
- name: Desplegar Oracle Database 23c AI con base de datos personalizada
  hosts: oracle_servers
  become: yes
  vars_files:
    - group_vars/vault.yml
  roles:
    - common
    - oracle_install
    - instituto_db
