---
- name: Instalar paquetes necesarios
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - php-mysql
      - mariadb-server
      - wget
      - unzip
      - python3-pymysql
      - python3-pip
      - python3-requests
      - python3-urllib3
    state: present
    update_cache: yes
  become: yes

- name: Iniciar y habilitar servicios
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - apache2
    - mariadb
  become: yes

- name: Asegurar que root puede autenticarse con contraseña en MariaDB
  ansible.builtin.shell: |
    mysql -u root <<EOF
    ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';
    FLUSH PRIVILEGES;
    EOF
  args:
    executable: /bin/bash
  become: yes

- name: Asegurar que la base de datos de WordPress existe
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: yes

- name: Crear usuario de WordPress en MySQL
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: "localhost"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: yes
# tasks file for wp_db
