---
- name: Crear la base de datos CDB con dbca para Oracle 23c AI
  ansible.builtin.command: >
    {{ oracle_home }}/bin/dbca -silent
    -createDatabase
    -templateName General_Purpose.dbc
    -gdbName {{ cdb_name }}
    -sid {{ oracle_sid }}
    -createAsContainerDatabase true
    -numberOfPDBs 1
    -pdbName {{ pdb_name }}
    -createListener LISTENER,port=1521
    -responseFile NO_VALUE
    -characterSet AL32UTF8
    -memoryMgmtType auto_sga
    -emConfiguration NONE
    -sysPassword {{ oracle_sys_password }}
    -systemPassword {{ oracle_system_password }}
    -dbsnmpPassword {{ oracle_dbsnmp_password }}
  become_user: oracle
