---
oracle_base: /u01/app/oracle
oracle_home: /u01/app/oracle/product/23c/dbhome_1
oracle_sid: ORCLCDB
cdb_name: ORCLCDB
pdb_name: ORCLPDB1
oracle_sys_password: Oracle123
oracle_system_password: Oracle123
oracle_dbsnmp_password: Oracle123
oracle_installer_zip: LINUX.X64_23c_database.zip
