- name: Buscar YAMLs de VM en {{ proxmox_image_path }}
  find:
    paths: "{{ proxmox_image_path }}"
    patterns: "*.yml"
    use_regex: false
    recurse: true
  register: vm_yaml_files

- name: Procesar cada VM encontrada
  include_tasks: process_vm.yml
  loop: "{{ vm_yaml_files.files }}"
  loop_control:
    label: "{{ item.path }}"
  vars:
    vmid: "{{ item.path.split('/')[-2] }}"
    vmname: "{{ item.path | basename | regex_replace('\\.yml$', '') }}"
