---
- name: Abrir el puerto 1521 en el firewall permanentemente
  ansible.builtin.firewalld:
    port: 1521/tcp
    permanent: true
    state: enabled
  notify: Reload firewall

- name: Cambiar HOST=localhost a HOST=0.0.0.0 en listener.ora
  ansible.builtin.replace:
    path: /opt/oracle/product/23ai/dbhomeFree/network/admin/listener.ora
    regexp: 'HOST\s*=\s*localhost'
    replace: 'HOST = 0.0.0.0'
  become: yes
  notify: Restart listener

- name: Añadir entrada INSTITUTO en tnsnames.ora
  ansible.builtin.blockinfile:
    path: /opt/oracle/product/23ai/dbhomeFree/network/admin/tnsnames.ora
    block: |
      INSTITUTO =
        (DESCRIPTION =
          (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.201)(PORT = 1521))
          (CONNECT_DATA =
            (SERVER = DEDICATED)
            (SERVICE_NAME = instituto)
          )
        )
    owner: oracle
    group: oinstall
    mode: '0644'

- name: Crear la PDB INSTITUTO en la CDB FREE
  ansible.builtin.shell: |
    export ORACLE_HOME=/opt/oracle/product/23ai/dbhomeFree
    export PATH=$ORACLE_HOME/bin:$PATH
    export ORACLE_SID=FREE
    echo "
    ALTER SESSION SET CONTAINER=CDB$ROOT;
    ALTER SYSTEM SET db_create_file_dest = '/opt/oracle/oradata/FREE' SCOPE=BOTH;
    CREATE PLUGGABLE DATABASE INSTITUTO
      ADMIN USER instituto_admin IDENTIFIED BY Oracle123;
    ALTER PLUGGABLE DATABASE INSTITUTO OPEN;
    " | $ORACLE_HOME/bin/sqlplus -s / as sysdba
  become_user: oracle

- name: Copiar script SQL para crear tablas y registros
  ansible.builtin.template:
    src: instituto_setup.sql.j2
    dest: /tmp/instituto_setup.sql
    owner: oracle
    group: oinstall
    mode: '0644'

- name: Otorgar privilegios a instituto_admin para crear tablas
  ansible.builtin.shell: |
    export ORACLE_HOME=/opt/oracle/product/23ai/dbhomeFree
    export PATH=$ORACLE_HOME/bin:$PATH
    export ORACLE_SID=FREE
    echo "
    ALTER SESSION SET CONTAINER=INSTITUTO;
    GRANT CONNECT, RESOURCE TO instituto_admin;
    " | $ORACLE_HOME/bin/sqlplus -s / as sysdba
  become_user: oracle

- name: Ejecutar script SQL como instituto_admin para crear tablas y registros
  ansible.builtin.shell: |
    export ORACLE_HOME=/opt/oracle/product/23ai/dbhomeFree
    export PATH=$ORACLE_HOME/bin:$PATH
    export ORACLE_SID=FREE
    $ORACLE_HOME/bin/sqlplus -s instituto_admin/Oracle123@//localhost:1521/instituto @/tmp/instituto_setup.sql
  become_user: oracle
