---
- name: Desplegar WordPress en dos máquinas con páginas personalizadas
  hosts: wordpress_servers
  become: yes

  vars_files:
    - group_vars/vault.yml  # Añade esta línea para incluir las variables cifradas
  
  roles:
    - wp_db
    - wordpress
    
