- name: Instalar Kea DHCPv4 y DHCPv6
  apt:
    name:
      - kea-dhcp4-server
      - kea-dhcp6-server
    update_cache: yes

- name: Configurar Kea DHCPv4
  template:
    src: kea-dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
  notify: Reiniciar Kea v4

- name: Configurar Kea DHCPv6
  template:
    src: kea-dhcp6.conf.j2
    dest: /etc/kea/kea-dhcp6.conf
  notify: Reiniciar Kea v6
