---
- name: Descargar WordPress manualmente usando wget
  ansible.builtin.shell: wget -O /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz
  args:
    creates: /tmp/wordpress.tar.gz
  become: yes

- name: Descomprimir WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
  become: yes

- name: Copiar archivo de configuración wp-config.php
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
  become: yes

- name: Descargar wp-cli.phar
  command: wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O /usr/local/bin/wp

- name: Dar permisos de ejecución a wp-cli
  file:
    path: /usr/local/bin/wp
    mode: '0755'
    owner: root
    group: root

- name: Establecer el título de la portada de WordPress según el servidor
  ansible.builtin.set_fact:
    wp_title: "{{ 'AnsibleRocks1' if inventory_hostname == 'wp1' else 'AnsibleRocks2' }}"

- name: Instalar WordPress automáticamente con wp-cli como root
  tags: wp-cli
  command: >
    wp core install
    --url="http://{{ ansible_host }}/"
    --title="{{ wp_title }}"
    --admin_user="{{ wp_admin_user }}"
    --admin_password="{{ wp_admin_password }}"
    --admin_email="{{ wp_admin_email }}"
    --path=/var/www/html/wordpress
    --allow-root
  become: yes
  args:
    chdir: /var/www/html/wordpress

- name: Ajustar permisos en /var/www/html
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  become: yes

- name: Establecer DocumentRoot de Apache a /var/www/html/wordpress
  ansible.builtin.lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '^\s*DocumentRoot'
    line: '    DocumentRoot /var/www/html/wordpress'
  become: yes

- name: Reiniciar Apache para aplicar cambios
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: yes
