# transfer_disks/tasks/proxmox_tasks.yml
- name: Crear directorio de destino en Proxmox para cada VM
  ansible.builtin.file:
    path: "/var/lib/vz/images/{{ item.vmid }}"
    state: directory
    mode: '0755'
  delegate_to: "{{ proxmox_host_ip }}"
  loop: "{{ transfer_list }}"
  loop_control:
    label: "{{ item.vmname }}"

- name: Copiar disco(s) de VM a Proxmox
  ansible.builtin.copy:
    src: "{{ disk }}"
    dest: "/var/lib/vz/images/{{ item.vmid }}/{{ disk | basename }}"
    mode: '0644'
  delegate_to: "{{ proxmox_host_ip }}"
  loop: "{{ transfer_list | subelements('disks') }}"
  loop_control:
    label: "{{ item.0.vmname }} - {{ item.1 }}"


- name: Copiar archivo YAML a Proxmox
  ansible.builtin.copy:
    src: "{{ item.yaml }}"
    dest: "/var/lib/vz/images/{{ item.vmid }}/{{ item.vmname }}.yml"
    mode: '0644'
  delegate_to: "{{ proxmox_host_ip }}"
  loop: "{{ transfer_list }}"
  loop_control:
    label: "{{ item.vmname }}"
