- name: Rsync de discos al host Proxmox por VM
  ansible.posix.synchronize:
    src: "{{ item.1 }}"
    dest: "{{ rsync_user }}@{{ proxmox_host }}:{{ proxmox_image_path }}/{{ item.0.vmid }}/"
    mode: push
    rsync_opts:
      - "--progress"
      - "--partial"
  loop: "{{ transfer_list | subelements('disks') }}"
  loop_control:
    label: "{{ item.0.vmname }} -> {{ item.1 }}"
  delegate_to: "{{ kvm_host }}"

- name: Rsync de YAMLs al host Proxmox por VM
  ansible.posix.synchronize:
    src: "{{ item.yaml }}"
    dest: "{{ rsync_user }}@{{ proxmox_host }}:{{ proxmox_image_path }}/{{ item.vmid }}/"
    mode: push
    rsync_opts:
      - "--progress"
      - "--partial"
  loop: "{{ transfer_list }}"
  loop_control:
    label: "{{ item.vmname }}"
  delegate_to: "{{ kvm_host }}"



