---
- name: Instalar paquetes necesarios para Oracle 23c AI
  ansible.builtin.yum:
    name:
      - oracle-database-preinstall-23ai
      - unzip
    state: present

- name: Configurar límites para Oracle
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
  loop:
    - "oracle soft nofile 1024"
    - "oracle hard nofile 65536"
    - "oracle soft nproc 16384"
    - "oracle hard nproc 16384"
