---
- name: Instalar paquetes necesarios
  ansible.builtin.yum:
    name: "{{ common_packages }}"
    state: present

- name: Instalar preinstalación de Oracle
  ansible.builtin.yum:
    name: oracle-database-preinstall-19c
    state: present

- name: Configurar parametros de kernel
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop: "{{ common_sysctl_params | dict2items }}"

- name: Configurar /etc/security/limits.conf
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
  loop: "{{ common_limits }}"

