---
- name: Alta de VMs en base de datos desde Proxmox
  hosts: proxmox_host
  gather_facts: false

  vars_files:
    - groups_vars/vault.yaml

  roles:
    - proxmox_info
    - database_insert
    - credentials_insert
