---
- name: Buscar XMLs en subdirectorios de imágenes
  find:
    paths: "{{ rsync_path }}"
    patterns: "*.xml"
    recurse: yes
  register: found_xmls

- name: DEBUG - Todos los XML encontrados
  debug:
    var: found_xmls.files

- name: Filtrar XMLs válidos
  set_fact:
    filtered_xmls: "{{ found_xmls.files }}"

- name: DEBUG - XMLs filtrados
  debug:
    var: filtered_xmls

- name: DEBUG - Paths de XML encontrados
  debug:
    msg: "{{ item.path }}"
  loop: "{{ filtered_xmls }}"

- name: Incluir tareas para crear cada VM desde su XML
  include_tasks: process_xml_vm.yml
  loop: "{{ filtered_xmls }}"
  loop_control:
    loop_var: xml_file
  vars:
    xml_file: "{{ xml_file.path }}"
